# Generated by Django 4.2.13 on 2026-05-08 15:33

import cinema.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Жанр (рус)')),
                ('name_ky', models.CharField(max_length=100, verbose_name='Жанр (кырг)')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название зала')),
                ('hall_type', models.CharField(choices=[('regular', 'Обычный'), ('vip', 'VIP')], default='regular', max_length=10, verbose_name='Тип зала')),
                ('rows', models.PositiveIntegerField(verbose_name='Количество рядов')),
                ('seats_per_row', models.PositiveIntegerField(verbose_name='Мест в ряду')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Название (рус)')),
                ('title_ky', models.CharField(max_length=200, verbose_name='Название (кырг)')),
                ('description_ru', models.TextField(verbose_name='Описание (рус)')),
                ('description_ky', models.TextField(verbose_name='Описание (кырг)')),
                ('poster', models.ImageField(upload_to='posters/', verbose_name='Постер')),
                ('trailer_url', models.URLField(blank=True, verbose_name='Трейлер (YouTube URL)')),
                ('duration', models.PositiveIntegerField(verbose_name='Длительность (мин)')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('age_rating', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], default='0+', max_length=3, verbose_name='Возрастной рейтинг')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Режиссёр')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_new', models.BooleanField(default=True, verbose_name='Новинка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('genres', models.ManyToManyField(blank=True, to='cinema.genre', verbose_name='Жанры')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField(verbose_name='Ряд')),
                ('number', models.PositiveIntegerField(verbose_name='Место')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='cinema.hall', verbose_name='Зал')),
            ],
            options={
                'verbose_name': 'Место',
                'verbose_name_plural': 'Места',
                'ordering': ['row', 'number'],
                'unique_together': {('hall', 'row', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена билета (сом)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.hall', verbose_name='Зал')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenings', to='cinema.movie', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Сеанс',
                'verbose_name_plural': 'Сеансы',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('booking_code', models.CharField(default=cinema.models.generate_booking_code, max_length=20, unique=True, verbose_name='Код бронирования')),
                ('status', models.CharField(choices=[('pending', 'Ожидание оплаты'), ('paid', 'Оплачено'), ('reserved', 'Зарезервировано (касса)'), ('cancelled', 'Отменено')], default='pending', max_length=10, verbose_name='Статус')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='Последние 4 цифры карты')),
                ('is_admin_booking', models.BooleanField(default=False, verbose_name='Касса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cinema.screening', verbose_name='Сеанс')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookedSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='cinema.booking')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_seats', to='cinema.seat')),
            ],
            options={
                'verbose_name': 'Забронированное место',
                'verbose_name_plural': 'Забронированные места',
                'unique_together': {('booking', 'seat')},
            },
        ),
    ]
