# Generated by Django 6.0.5 on 2026-06-16 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_paybox_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description_ky',
            field=models.TextField(blank=True, default='', verbose_name='Описание (кырг)'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (рус)'),
        ),
    ]
