# Generated by Django 6.0.5 on 2026-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_make_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_note',
            field=models.TextField(blank=True, default='', verbose_name='Примечание по оплате'),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Чек оплаты'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('receipt_uploaded', 'Чек загружен'), ('paid', 'Оплачено'), ('reserved', 'Зарезервировано (касса)'), ('cancelled', 'Отменено')], default='pending', max_length=20, verbose_name='Статус'),
        ),
    ]
