# Generated by Django 6.0.5 on 2026-09-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0005_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Вход по билету'),
        ),
    ]
